# Configuração da conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/secret_wish
spring.datasource.username=root
spring.datasource.password=1234

# Estratégia de atualização do banco (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.jpa.open-in-view=false
spring.ai.openai.api-key=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